from enum import Enum

class EventType(str, Enum):
    """System event types for Vault."""
    NODE_ONLINE = "NODE_ONLINE"
    NODE_OFFLINE = "NODE_OFFLINE"
    NODE_PARTITIONED = "NODE_PARTITIONED"
    
    # Phase 2 Object Storage Events
    OBJECT_UPLOAD_STARTED = "OBJECT_UPLOAD_STARTED"
    OBJECT_CREATED = "OBJECT_CREATED"
    REPLICA_CREATED = "REPLICA_CREATED"
    OBJECT_VERIFIED = "OBJECT_VERIFIED"
    OBJECT_DOWNLOADED = "OBJECT_DOWNLOADED"
    OBJECT_READ = "OBJECT_READ"
    OBJECT_DELETED = "OBJECT_DELETED"
    OBJECT_UPLOAD_FAILED = "OBJECT_UPLOAD_FAILED"
    
    # Chaos & Healing Events
    OBJECT_REPAIRED = "OBJECT_REPAIRED"
    CORRUPTION_DETECTED = "CORRUPTION_DETECTED"
    REBALANCE_STARTED = "REBALANCE_STARTED"
    REBALANCE_COMPLETED = "REBALANCE_COMPLETED"
